In [144]:
#hiring experience candidate predict salaries bised on there experiance test_score and interview_score 

import pandas as pd # linear algebra
import numpy as np # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn import linear_model 
from sklearn.model_selection import train_test_split #Split arrays or matrices into random train and test subsets.


In [145]:
df = pd.read_csv('linear_reg_ex/hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [146]:
df.columns

Index(['experience', 'test_score(out of 10)', 'interview_score(out of 10)',
       'salary($)'],
      dtype='object')

In [147]:
#remane columns

df.rename(columns = {df.columns[1]: "test_score", df.columns[2] : "interview_score", df.columns[3]: "salary"}, inplace=True)
df.columns

Index(['experience', 'test_score', 'interview_score', 'salary'], dtype='object')

In [148]:
df.experience = df.experience.fillna('zero')
df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [149]:
df.test_score.median()
#reg = linear_model.LinearRegression()
#reg.fit(df.drop('salary',axis='columns'),df.salary)

8.0

In [150]:
df.test_score = df.test_score.fillna(df.test_score.median())
df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [151]:
#ordinal label encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
order_label = {"zero":0, "two":2, "three":3, "five":5, "seven":7, "ten":10, "eleven":11}
df['experience'] = df['experience'].map(order_label)
df
#df.experience.value_counts()


experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [152]:
X = df.drop('salary', axis="columns")
X

experience  test_score  interview_score
0           0         8.0                9
1           0         8.0                6
2           5         6.0                7
3           2        10.0               10
4           7         9.0                6
5           3         7.0               10
6          10         8.0                7
7          11         7.0                8

In [153]:
y = df.salary
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [154]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [155]:
# Create linear regression object
reg = linear_model.LinearRegression()

In [156]:
reg.fit(X_train, y_train)

LinearRegression()

In [157]:
X_test

experience  test_score  interview_score
2           5         6.0                7
3           2        10.0               10

In [158]:
reg.predict(X_test)

array([57455.49012816, 63712.15794943])

In [161]:
reg.score(X_test, y_test)

0.3493545891913713

In [162]:
reg.fit(X, y)

LinearRegression()

In [163]:
reg.predict([[2,9,10]])

/home/daud/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([62026.9286754])

In [164]:
reg.predict([[12,10,10]])

/home/daud/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])

In [165]:
reg.score(X, y)

0.9616780002577959

In [166]:
reg.predict([[10,8,7]])

/home/daud/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([76069.1411936])